### ISSUE TITLE
fix concurrent map writes in exclient

### ISSUE THREAD

**Issue by calvix** [exmonitor/exmonitor#22]
fix concurrent map writes in exclient

```
fatal error: concurrent map writes

goroutine 8 [running]:
runtime.throw(0x9e7099, 0x15)
	/usr/lib/golang/src/runtime/panic.go:608 +0x72 fp=0xc000187c30 sp=0xc000187c00 pc=0x42c342
runtime.mapassign_fast64(0x926ea0, 0xc0000a3e00, 0xb4, 0x0)
	/usr/lib/golang/src/runtime/map_fast64.go:172 +0x2ea fp=0xc000187c70 sp=0xc000187c30 pc=0x41259a
github.com/exmonitor/watcher/vendor/github.com/exmonitor/exclient/database/multi/cache.(*SQL_GetServices).CacheData(0xc0000ac158, 0xb4, 0x0, 0x0, 0x0)
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/vendor/github.com/exmonitor/exclient/database/multi/cache/getServices.go:49 +0x9d fp=0xc000187cd0 sp=0xc000187c70 pc=0x85e5dd
github.com/exmonitor/watcher/vendor/github.com/exmonitor/exclient/database/multi.(*Client).SQL_GetServices(0xc0000aecc0, 0xb4, 0x2b, 0xc00062ffa8, 0x2, 0x2, 0x0)
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/vendor/github.com/exmonitor/exclient/database/multi/sql.go:215 +0x711 fp=0xc000187ef8 sp=0xc000187cd0 pc=0x862751
github.com/exmonitor/watcher/interval.(*IntervalGroup).Boot(0xc000222090)
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/interval/interval.go:82 +0x3fd fp=0xc000187fd8 sp=0xc000187ef8 pc=0x89228d
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000187fe0 sp=0xc000187fd8 pc=0x458e91
created by github.com/exmonitor/watcher/interval.InitIntervalGroups
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/interval/interval.go:170 +0x190

goroutine 1 [select (no cases), 8 minutes]:
main.mainExecute(0xe8e300, 0xc00013c100, 0x0, 0x8)
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/main.go:153 +0x5a3
github.com/exmonitor/watcher/vendor/github.com/spf13/cobra.(*Command).execute(0xe8e300, 0xc0000b2010, 0x8, 0x8, 0xe8e300, 0xc0000b2010)
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/vendor/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/exmonitor/watcher/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xe8e300, 0x9f694d, 0x41, 0xc0000c35e0)
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/exmonitor/watcher/vendor/github.com/spf13/cobra.(*Command).Execute(0xe8e300, 0xe93cb0, 0x9e3339)
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/main.go:79 +0x61c

goroutine 19 [syscall, 8 minutes]:
os/signal.signal_recv(0x0)
	/usr/lib/golang/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/usr/lib/golang/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/lib/golang/src/os/signal/signal_unix.go:29 +0x41

goroutine 20 [select, 8 minutes]:
database/sql.(*DB).connectionOpener(0xc0001440c0, 0xa66380, 0xc0000b03c0)
	/usr/lib/golang/src/database/sql/sql.go:1001 +0xe8
created by database/sql.OpenDB
	/usr/lib/golang/src/database/sql/sql.go:671 +0x15d

goroutine 21 [select]:
database/sql.(*DB).connectionResetter(0xc0001440c0, 0xa66380, 0xc0000b03c0)
	/usr/lib/golang/src/database/sql/sql.go:1014 +0xfb
created by database/sql.OpenDB
	/usr/lib/golang/src/database/sql/sql.go:672 +0x193

goroutine 39 [chan receive, 8 minutes]:
main.catchOSSignals.func1(0xc0000945a0, 0xc0000a3350, 0xa677c0, 0xc0000aecc0)
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/main.go:162 +0x52
created by main.catchOSSignals
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/main.go:161 +0xe6

goroutine 26 [select, 8 minutes]:
github.com/exmonitor/watcher/vendor/github.com/olivere/elastic.(*Client).sniffer(0xc00016c000)
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/vendor/github.com/olivere/elastic/client.go:850 +0x169
created by github.com/exmonitor/watcher/vendor/github.com/olivere/elastic.DialContext
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/vendor/github.com/olivere/elastic/client.go:394 +0x622

goroutine 27 [select, 1 minutes]:
github.com/exmonitor/watcher/vendor/github.com/olivere/elastic.(*Client).healthchecker(0xc00016c000)
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/vendor/github.com/olivere/elastic/client.go:1044 +0x16b
created by github.com/exmonitor/watcher/vendor/github.com/olivere/elastic.DialContext
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/vendor/github.com/olivere/elastic/client.go:397 +0x5fe

goroutine 5 [chan receive]:
github.com/exmonitor/watcher/interval.(*IntervalGroup).Boot(0xc000222000)
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/interval/interval.go:78 +0x385
created by github.com/exmonitor/watcher/interval.InitIntervalGroups
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/interval/interval.go:170 +0x190

goroutine 6 [chan receive, 1 minutes]:
github.com/exmonitor/watcher/interval.(*IntervalGroup).Boot(0xc000222030)
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/interval/interval.go:78 +0x385
created by github.com/exmonitor/watcher/interval.InitIntervalGroups
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/interval/interval.go:170 +0x190

goroutine 7 [chan receive, 2 minutes]:
github.com/exmonitor/watcher/interval.(*IntervalGroup).Boot(0xc000222060)
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/interval/interval.go:78 +0x385
created by github.com/exmonitor/watcher/interval.InitIntervalGroups
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/interval/interval.go:170 +0x190

goroutine 9 [runnable]:
strconv.rightShift(0xc0001e9418, 0x34)
	/usr/lib/golang/src/strconv/decimal.go:110 +0x1b8
strconv.(*decimal).Shift(0xc00018a418, 0xffffffffffffffcc)
	/usr/lib/golang/src/strconv/decimal.go:330 +0xbf
strconv.bigFtoa(0xc00061a128, 0x1, 0x44, 0x4, 0x66, 0x1944b7f5a5332b, 0x0, 0xe5ac00, 0x1c, 0x203000, ...)
	/usr/lib/golang/src/strconv/ftoa.go:159 +0xaa
strconv.genericFtoa(0xc00061a128, 0x1, 0x44, 0x3ff944b7f5a5332b, 0x66, 0x4, 0x40, 0x454290, 0x7f1cd6c33000, 0x4)
	/usr/lib/golang/src/strconv/ftoa.go:150 +0x3b1
strconv.AppendFloat(0xc00061a128, 0x1, 0x44, 0x3ff944b7f5a5332b, 0xc00018aa66, 0x4, 0x40, 0x756ea17b96e963, 0x83cb27c5d97ef693, 0xc00018aa00)
	/usr/lib/golang/src/strconv/ftoa.go:52 +0x75
fmt.(*fmt).fmtFloat(0xc00061a100, 0x3ff944b7f5a5332b, 0x40, 0x66, 0x6)
	/usr/lib/golang/src/fmt/format.go:459 +0x9f
fmt.(*pp).fmtFloat(0xc00061a0c0, 0x3ff944b7f5a5332b, 0x40, 0x66)
	/usr/lib/golang/src/fmt/print.go:402 +0x6a
fmt.(*pp).printArg(0xc00061a0c0, 0x8f6440, 0xc000458220, 0x66)
	/usr/lib/golang/src/fmt/print.go:643 +0x30e
fmt.(*pp).doPrintf(0xc00061a0c0, 0x9df694, 0x4, 0xc0001e9cb0, 0x1, 0x1)
	/usr/lib/golang/src/fmt/print.go:1099 +0x40f
fmt.Sprintf(0x9df694, 0x4, 0xc00018acb0, 0x1, 0x1, 0xe93900, 0x18190d)
	/usr/lib/golang/src/fmt/print.go:203 +0x66
github.com/exmonitor/watcher/vendor/github.com/exmonitor/chronos.(*TimeInterval).StringMilisec(0xc0004ba390, 0xf0, 0x0)
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/vendor/github.com/exmonitor/chronos/chronos.go:41 +0x17c
github.com/exmonitor/watcher/vendor/github.com/exmonitor/exclient/database/multi.(*Client).SQL_GetServices(0xc0000aecc0, 0xf0, 0x2b, 0xc0005e9fa8, 0x2, 0x2, 0x0)
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/vendor/github.com/exmonitor/exclient/database/multi/sql.go:220 +0x5dd
github.com/exmonitor/watcher/interval.(*IntervalGroup).Boot(0xc0002220c0)
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/interval/interval.go:82 +0x3fd
created by github.com/exmonitor/watcher/interval.InitIntervalGroups
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/interval/interval.go:170 +0x190

goroutine 10 [chan receive, 1 minutes]:
github.com/exmonitor/watcher/interval.(*IntervalGroup).Boot(0xc0002220f0)
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/interval/interval.go:78 +0x385
created by github.com/exmonitor/watcher/interval.InitIntervalGroups
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/interval/interval.go:170 +0x190

goroutine 11 [sleep, 1 minutes]:
time.Sleep(0x3b9aca00)
	/usr/lib/golang/src/runtime/time.go:105 +0x14f
github.com/exmonitor/watcher/interval.intervalTick(0x12c, 0xc000148060, 0x0)
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/interval/interval.go:129 +0x90
created by github.com/exmonitor/watcher/interval.(*IntervalGroup).Boot
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/interval/interval.go:72 +0x7f

goroutine 12 [sleep, 1 minutes]:
time.Sleep(0x3b9aca00)
	/usr/lib/golang/src/runtime/time.go:105 +0x14f
github.com/exmonitor/watcher/interval.intervalTick(0x1e, 0xc0001480c0, 0x0)
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/interval/interval.go:129 +0x90
created by github.com/exmonitor/watcher/interval.(*IntervalGroup).Boot
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/interval/interval.go:72 +0x7f

goroutine 13 [sleep, 1 minutes]:
time.Sleep(0x3b9aca00)
	/usr/lib/golang/src/runtime/time.go:105 +0x14f
github.com/exmonitor/watcher/interval.intervalTick(0x3c, 0xc000148120, 0x0)
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/interval/interval.go:129 +0x90
created by github.com/exmonitor/watcher/interval.(*IntervalGroup).Boot
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/interval/interval.go:72 +0x7f

goroutine 14 [sleep, 1 minutes]:
time.Sleep(0x5f5e100)
	/usr/lib/golang/src/runtime/time.go:105 +0x14f
github.com/exmonitor/watcher/interval.intervalTick(0x78, 0xc000148180, 0x0)
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/interval/interval.go:132 +0x30
created by github.com/exmonitor/watcher/interval.(*IntervalGroup).Boot
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/interval/interval.go:72 +0x7f

goroutine 15 [sleep, 1 minutes]:
time.Sleep(0x3b9aca00)
	/usr/lib/golang/src/runtime/time.go:105 +0x14f
github.com/exmonitor/watcher/interval.intervalTick(0xb4, 0xc0001481e0, 0x0)
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/interval/interval.go:129 +0x90
created by github.com/exmonitor/watcher/interval.(*IntervalGroup).Boot
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/interval/interval.go:72 +0x7f

goroutine 16 [sleep, 1 minutes]:
time.Sleep(0x3b9aca00)
	/usr/lib/golang/src/runtime/time.go:105 +0x14f
github.com/exmonitor/watcher/interval.intervalTick(0xf0, 0xc000148240, 0x0)
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/interval/interval.go:129 +0x90
created by github.com/exmonitor/watcher/interval.(*IntervalGroup).Boot
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/interval/interval.go:72 +0x7f

goroutine 42 [select, 8 minutes]:
github.com/exmonitor/watcher/vendor/github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher.func1(0xc000170060, 0xc0005480c0, 0xc000166120)
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/vendor/github.com/go-sql-driver/mysql/connection_go18.go:178 +0xbf
created by github.com/exmonitor/watcher/vendor/github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/vendor/github.com/go-sql-driver/mysql/connection_go18.go:175 +0xbe

goroutine 142 [select]:
net.(*Resolver).LookupIPAddr(0xe933a0, 0xa663c0, 0xc0000a8010, 0xc000458160, 0x9, 0xc00045816a, 0x3, 0x1bb, 0x0, 0x0)
	/usr/lib/golang/src/net/lookup.go:227 +0x55f
net.(*Resolver).internetAddrList(0xe933a0, 0xa663c0, 0xc0000a8010, 0x9df615, 0x3, 0xc000458160, 0xd, 0x0, 0x0, 0x0, ...)
	/usr/lib/golang/src/net/ipsock.go:279 +0x614
net.(*Resolver).resolveAddrList(0xe933a0, 0xa663c0, 0xc0000a8010, 0x9df84c, 0x4, 0x9df615, 0x3, 0xc000458160, 0xd, 0x0, ...)
	/usr/lib/golang/src/net/dial.go:202 +0x4fb
net.(*Dialer).DialContext(0xe939c0, 0xa663c0, 0xc0000a8010, 0x9df615, 0x3, 0xc000458160, 0xd, 0x0, 0x0, 0x0, ...)
	/usr/lib/golang/src/net/dial.go:384 +0x201
net/http.(*Transport).dial(0xc00064e000, 0xa663c0, 0xc0000a8010, 0x9df615, 0x3, 0xc000458160, 0xd, 0x7f1cd00fa030, 0x10, 0x4, ...)
	/usr/lib/golang/src/net/http/transport.go:925 +0x17f
net/http.(*Transport).dialConn(0xc00064e000, 0xa663c0, 0xc0000a8010, 0x0, 0xc00043b410, 0x5, 0xc000458160, 0xd, 0x0, 0xc0000f0240, ...)
	/usr/lib/golang/src/net/http/transport.go:1240 +0x313
net/http.(*Transport).getConn.func4(0xc00064e000, 0xa663c0, 0xc0000a8010, 0xc000650180, 0xc000522120)
	/usr/lib/golang/src/net/http/transport.go:999 +0x6e
created by net/http.(*Transport).getConn
	/usr/lib/golang/src/net/http/transport.go:998 +0x3d7

goroutine 368 [IO wait]:
internal/poll.runtime_pollWait(0x7f1cd21d2950, 0x72, 0xc0005560e8)
	/usr/lib/golang/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc000414898, 0x72, 0xffffffffffffff00, 0xa63080, 0xe5a4c8)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc000414898, 0xc000200600, 0x200, 0x200)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc000414880, 0xc000200600, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc000414880, 0xc000200600, 0x200, 0x200, 0xc0005561f8, 0x442127, 0x200)
	/usr/lib/golang/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00015c090, 0xc000200600, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/net/net.go:177 +0x68
net.dnsPacketRoundTrip(0xa67be0, 0xc00015c090, 0x72657473616d6f8b, 0x2e7a632e, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/lib/golang/src/net/dnsclient_unix.go:82 +0x176
net.(*Resolver).exchange(0xe933a0, 0xa66380, 0xc00024e340, 0xc0000a9160, 0xe, 0x632e72657473616d, 0x2e7a, 0x0, 0x0, 0x0, ...)
	/usr/lib/golang/src/net/dnsclient_unix.go:155 +0x476
net.(*Resolver).tryOneName(0xe933a0, 0xa66380, 0xc00024e340, 0xc0000c3e00, 0xc00042c450, 0xa, 0xc00006001c, 0x0, 0x0, 0x0, ...)
	/usr/lib/golang/src/net/dnsclient_unix.go:245 +0x368
net.(*Resolver).goLookupIPCNAMEOrder.func1(0xe933a0, 0xa66380, 0xc00024e340, 0xc0000c3e00, 0xc0004304a0, 0xc000170a20, 0x1c)
	/usr/lib/golang/src/net/dnsclient_unix.go:585 +0xba
created by net.(*Resolver).goLookupIPCNAMEOrder
	/usr/lib/golang/src/net/dnsclient_unix.go:584 +0x29f

goroutine 51 [select, 8 minutes]:
github.com/exmonitor/watcher/vendor/github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher.func1(0xc0000ae4e0, 0xc0001f80c0, 0xc0000943c0)
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/vendor/github.com/go-sql-driver/mysql/connection_go18.go:178 +0xbf
created by github.com/exmonitor/watcher/vendor/github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/vendor/github.com/go-sql-driver/mysql/connection_go18.go:175 +0xbe

goroutine 452 [select]:
net.(*Resolver).LookupIPAddr(0xe933a0, 0xa66400, 0xc0001e0600, 0xc0004581b0, 0x9, 0xc0004581ba, 0x4, 0x4d2, 0x0, 0x0)
	/usr/lib/golang/src/net/lookup.go:227 +0x55f
net.(*Resolver).internetAddrList(0xe933a0, 0xa66400, 0xc0001e0600, 0x9df615, 0x3, 0xc0004581b0, 0xe, 0x0, 0x0, 0x0, ...)
	/usr/lib/golang/src/net/ipsock.go:279 +0x614
net.(*Resolver).resolveAddrList(0xe933a0, 0xa66400, 0xc0001e0600, 0x9df84c, 0x4, 0x9df615, 0x3, 0xc0004581b0, 0xe, 0x0, ...)
	/usr/lib/golang/src/net/dial.go:202 +0x4fb
net.(*Dialer).DialContext(0xc0005aee60, 0xa663c0, 0xc0000a8010, 0x9df615, 0x3, 0xc0004581b0, 0xe, 0x0, 0x0, 0x0, ...)
	/usr/lib/golang/src/net/dial.go:384 +0x201
net.(*Dialer).Dial(0xc000596e60, 0x9df615, 0x3, 0xc0004581b0, 0xe, 0xc00061a000, 0xc000596ec0, 0x890fc9, 0x9dfa08)
	/usr/lib/golang/src/net/dial.go:329 +0x75
net.DialTimeout(0x9df615, 0x3, 0xc0004581b0, 0xe, 0x12a05f200, 0xa677c0, 0xc0000aecc0, 0xc0001e0480, 0x0)
	/usr/lib/golang/src/net/dial.go:315 +0x9d
github.com/exmonitor/watcher/interval/tcp.(*Check).doCheck(0xc000586070, 0x0)
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/interval/tcp/tcp.go:114 +0x1ae
github.com/exmonitor/watcher/interval/tcp.(*Check).RunCheck(0xc000586070)
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/interval/tcp/tcp.go:93 +0x5b
created by github.com/exmonitor/watcher/interval.(*IntervalGroup).Boot
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/interval/interval.go:110 +0x231

goroutine 236 [select, 1 minutes]:
net/http.(*persistConn).writeLoop(0xc00054c240)
	/usr/lib/golang/src/net/http/transport.go:1885 +0x113
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1339 +0x966

goroutine 141 [select]:
net/http.setRequestCancel.func3(0x0, 0xc000650120, 0xc000172000, 0xc00045814c, 0xc0005220c0)
	/usr/lib/golang/src/net/http/client.go:321 +0xcf
created by net/http.setRequestCancel
	/usr/lib/golang/src/net/http/client.go:320 +0x24e

goroutine 140 [select]:
net/http.(*Transport).getConn(0xc00064e000, 0xc000650150, 0x0, 0xc00043b410, 0x5, 0xc000458160, 0xd, 0x0, 0x0, 0x8fa040)
	/usr/lib/golang/src/net/http/transport.go:1004 +0x58e
net/http.(*Transport).roundTrip(0xc00064e000, 0xc000652100, 0xc000650120, 0xc00045814c, 0xc000458150)
	/usr/lib/golang/src/net/http/transport.go:451 +0x690
net/http.(*Transport).RoundTrip(0xc00064e000, 0xc000652100, 0xc00064e000, 0xbf04e6a94041d559, 0x7acd938d80)
	/usr/lib/golang/src/net/http/roundtrip.go:17 +0x35
net/http.send(0xc000652000, 0xa62220, 0xc00064e000, 0xbf04e6a94041d559, 0x7acd938d80, 0xe93900, 0xc000524020, 0xbf04e6a94041d559, 0xc0005aec48, 0x1)
	/usr/lib/golang/src/net/http/client.go:250 +0x14b
net/http.(*Client).send(0xc000650000, 0xc000652000, 0xbf04e6a94041d559, 0x7acd938d80, 0xe93900, 0xc000524020, 0x0, 0x1, 0xc00056a600)
	/usr/lib/golang/src/net/http/client.go:174 +0xfa
net/http.(*Client).do(0xc000650000, 0xc000652000, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/net/http/client.go:641 +0x2a8
net/http.(*Client).Do(0xc000650000, 0xc000652000, 0xc00043b410, 0x2a, 0xa62520)
	/usr/lib/golang/src/net/http/client.go:509 +0x35
github.com/exmonitor/watcher/interval/http.(*Check).doCheck(0xc000648000, 0xc00043b3e0)
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/interval/http/http.go:255 +0x3ab
github.com/exmonitor/watcher/interval/http.(*Check).RunCheck(0xc000648000)
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/interval/http/http.go:200 +0x5b
created by github.com/exmonitor/watcher/interval.(*IntervalGroup).Boot
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/interval/interval.go:110 +0x231

goroutine 453 [select, 1 minutes]:
net.(*Resolver).LookupIPAddr(0xe933a0, 0xa66400, 0xc000584f00, 0xc00040e330, 0x9, 0xc00040e33a, 0x2, 0x50, 0x0, 0x0)
	/usr/lib/golang/src/net/lookup.go:227 +0x55f
net.(*Resolver).internetAddrList(0xe933a0, 0xa66400, 0xc000584f00, 0x9df615, 0x3, 0xc00040e330, 0xc, 0x0, 0x0, 0x0, ...)
	/usr/lib/golang/src/net/ipsock.go:279 +0x614
net.(*Resolver).resolveAddrList(0xe933a0, 0xa66400, 0xc000584f00, 0x9df84c, 0x4, 0x9df615, 0x3, 0xc00040e330, 0xc, 0x0, ...)
	/usr/lib/golang/src/net/dial.go:202 +0x4fb
net.(*Dialer).DialContext(0xc000627e60, 0xa663c0, 0xc0000a8010, 0x9df615, 0x3, 0xc00040e330, 0xc, 0x0, 0x0, 0x0, ...)
	/usr/lib/golang/src/net/dial.go:384 +0x201
net.(*Dialer).Dial(0xc000298660, 0x9df615, 0x3, 0xc00040e330, 0xc, 0xc00035e000, 0xc0002986c0, 0x890fc9, 0x9dfa08)
	/usr/lib/golang/src/net/dial.go:329 +0x75
net.DialTimeout(0x9df615, 0x3, 0xc00040e330, 0xc, 0x12a05f200, 0xa677c0, 0xc0000aecc0, 0xc000584ea0, 0x0)
	/usr/lib/golang/src/net/dial.go:315 +0x9d
github.com/exmonitor/watcher/interval/tcp.(*Check).doCheck(0xc0005860e0, 0x0)
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/interval/tcp/tcp.go:114 +0x1ae
github.com/exmonitor/watcher/interval/tcp.(*Check).RunCheck(0xc0005860e0)
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/interval/tcp/tcp.go:93 +0x5b
created by github.com/exmonitor/watcher/interval.(*IntervalGroup).Boot
	/home/calvix/giantswarm/src/github.com/exmonitor/watcher/interval/interval.go:110 +0x231

goroutine 454 [chan receive]:
net.(*Resolver).goLookupIPCNAMEOrder(0xe933a0, 0xa66380, 0xc00024e340, 0xc00040e330, 0x9, 0x1, 0x0, 0x0, 0xe93900, 0x0, ...)
	/usr/lib/golang/src/net/dnsclient_unix.go:592 +0x767
net.(*Resolver).lookupIP(0xe933a0, 0xa66380, 0xc00024e340, 0xc00040e330, 0x9, 0xc0002986c0, 0xc00023cd80, 0xc000030400, 0x9df615, 0x3)
	/usr/lib/golang/src/net/lookup_unix.go:101 +0xd7
net.(*Resolver).lookupIP-fm(0xa66380, 0xc00024e340, 0xc00040e330, 0x9, 0x42b0a2, 0x8, 0xc000030400, 0x0, 0xc0002986a0)
	/usr/lib/golang/src/net/lookup.go:207 +0x56
net.glob..func1(0xa66380, 0xc00024e340, 0xc0003e25d0, 0xc00040e330, 0x9, 0xc000298798, 0x890cce, 0x9df615, 0x3, 0xc00040e330)
	/usr/lib/golang/src/net/hook.go:19 +0x52
net.(*Resolver).LookupIPAddr.func1(0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/net/lookup.go:221 +0xd8
internal/singleflight.(*Group).doCall(0xe933b0, 0xc0001d2500, 0xc00040e330, 0x9, 0xc000262db0)
	/usr/lib/golang/src/internal/singleflight/singleflight.go:95 +0x2e
created by internal/singleflight.(*Group).DoChan
	/usr/lib/golang/src/internal/singleflight/singleflight.go:88 +0x2a0

goroutine 235 [IO wait, 1 minutes]:
internal/poll.runtime_pollWait(0x7f1cd21d2a20, 0x72, 0xc000185a88)
	/usr/lib/golang/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc00013ce98, 0x72, 0xffffffffffffff00, 0xa63080, 0xe5a4c8)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc00013ce98, 0xc0001d5000, 0x1000, 0x1000)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc00013ce80, 0xc0001d5000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc00013ce80, 0xc0001d5000, 0x1000, 0x1000, 0xc000185b70, 0x455a80, 0xc00023c900)
	/usr/lib/golang/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0002ba0d0, 0xc0001d5000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/net/net.go:177 +0x68
net/http.(*persistConn).Read(0xc00054c240, 0xc0001d5000, 0x1000, 0x1000, 0xc000185c70, 0x4067e5, 0xc0000f0900)
	/usr/lib/golang/src/net/http/transport.go:1497 +0x75
bufio.(*Reader).fill(0xc0002b3200)
	/usr/lib/golang/src/bufio/bufio.go:100 +0x106
bufio.(*Reader).Peek(0xc0002b3200, 0x1, 0x0, 0x0, 0x1, 0xc0002c48a0, 0x0)
	/usr/lib/golang/src/bufio/bufio.go:132 +0x3f
net/http.(*persistConn).readLoop(0xc00054c240)
	/usr/lib/golang/src/net/http/transport.go:1645 +0x1a2
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1338 +0x941

goroutine 367 [IO wait]:
internal/poll.runtime_pollWait(0x7f1cd21d2c90, 0x72, 0xc0005e80e8)
	/usr/lib/golang/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc000428a18, 0x72, 0xffffffffffffff00, 0xa63080, 0xe5a4c8)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc000428a18, 0xc0000d4600, 0x200, 0x200)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc000428a00, 0xc0000d4600, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc000428a00, 0xc0000d4600, 0x200, 0x200, 0xc0005e81f8, 0x442127, 0x200)
	/usr/lib/golang/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00000e0c0, 0xc0000d4600, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/net/net.go:177 +0x68
net.dnsPacketRoundTrip(0xa67be0, 0xc00000e0c0, 0x72657473616d1b3a, 0x2e7a632e, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/lib/golang/src/net/dnsclient_unix.go:82 +0x176
net.(*Resolver).exchange(0xe933a0, 0xa66380, 0xc00024e340, 0xc0000a9160, 0xe, 0x632e72657473616d, 0x2e7a, 0x0, 0x0, 0x0, ...)
	/usr/lib/golang/src/net/dnsclient_unix.go:155 +0x476
net.(*Resolver).tryOneName(0xe933a0, 0xa66380, 0xc00024e340, 0xc0000c3e00, 0xc00042c450, 0xa, 0xe90001, 0x0, 0x0, 0x0, ...)
	/usr/lib/golang/src/net/dnsclient_unix.go:245 +0x368
net.(*Resolver).goLookupIPCNAMEOrder.func1(0xe933a0, 0xa66380, 0xc00024e340, 0xc0000c3e00, 0xc0004304a0, 0xc000170a20, 0x1)
	/usr/lib/golang/src/net/dnsclient_unix.go:585 +0xba
created by net.(*Resolver).goLookupIPCNAMEOrder
	/usr/lib/golang/src/net/dnsclient_unix.go:584 +
```

**Comment by calvix** [comment]
looks like concurrent map write in the sql cache system

possible solutions:
* introduce mutex for writing into cache and have SaveData function in cache as atomic

**Comment by calvix** [comment]
Still need to do mutex sync in firefly

**Comment by calvix** [comment]
done, mapwrites should be now atomic and secured with `sync.Mutex`
